### ISSUE TITLE
[japi] api.joomla.org anchor links too low - result hidden

### ISSUE THREAD

**Issue by photodude** [joomla/joomla-websites#322]
#### Please describe the problem or your issue
Anchor links to class methods are too low, often the method is hidden in the fixed header when you click on the anchor link.

Example (click any method get the same result)
https://api.joomla.org/cms-3/classes/JCacheController.html#method_getInstance

Basically, the fixed headers cause on offset that needs to be dealt with in the CSS

#### Proposed CSS Fix
Just add the CSS3 `:target:before` selector to the page. This will apply to all the anchors automatically.

```css
:target:before{
	display: block;
	content: " ";
	margin-top: -90px;
	height: 90px;
	visibility: hidden;
}
```
I calculated the header to be 89px and chose 90px for simplicity. increasing or decreasing the value will allow fine tuning the correction.
